# Generated by Django 2.1.8 on 2019-10-30 04:23

from django.db import migrations, models
import django.db.models.deletion
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Product Owner'), (2, 'Developer Team')], default=2)),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('estimate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Description', models.CharField(max_length=400)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Not Yet Started'), (2, 'In Progress'), (3, 'Done')], default=1)),
                ('priority', models.IntegerField(blank=True, default=None, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickedPBI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.PBI')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('estimate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Description', models.CharField(max_length=400)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Not Yet Started'), (2, 'In Progress'), (3, 'Done')], default=1)),
                ('pbiPicked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.PickedPBI')),
            ],
        ),
        migrations.AddField(
            model_name='pickedpbi',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Project'),
        ),
        migrations.AddField(
            model_name='pbi',
            name='project',
            field=models.ForeignKey(default=myApp.models.get_default_project, on_delete=django.db.models.deletion.CASCADE, to='myApp.Project'),
        ),
        migrations.AddField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Project'),
        ),
        migrations.AddField(
            model_name='manager',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Project'),
        ),
    ]
