# Generated by Django 2.1.8 on 2019-10-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_pbi_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myApp.Project'),
            preserve_default=False,
        ),
    ]
